-- HERÈA'26 Supabase setup
-- Run this complete script in the Supabase SQL Editor.

-- 1. Registrations table
CREATE TABLE IF NOT EXISTS public.registrations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  registration_id TEXT UNIQUE NOT NULL,
  full_name TEXT NOT NULL,
  team_leader_name TEXT,
  teammate_name TEXT,
  college_name TEXT NOT NULL,
  department TEXT NOT NULL,
  email TEXT NOT NULL,
  whatsapp TEXT NOT NULL,
  selected_event TEXT NOT NULL,
  payment_screenshot TEXT NOT NULL,
  payment_status TEXT NOT NULL DEFAULT 'Pending',
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Also add the team-member columns when upgrading an existing table.
ALTER TABLE public.registrations
  ADD COLUMN IF NOT EXISTS team_leader_name TEXT,
  ADD COLUMN IF NOT EXISTS teammate_name TEXT;

ALTER TABLE public.registrations ENABLE ROW LEVEL SECURITY;

-- Remove the policies from earlier versions of this setup before recreating them.
DROP POLICY IF EXISTS "Allow public inserts" ON public.registrations;
DROP POLICY IF EXISTS "Allow authenticated view" ON public.registrations;
DROP POLICY IF EXISTS "Allow authenticated update" ON public.registrations;
DROP POLICY IF EXISTS "Public can submit registrations" ON public.registrations;
DROP POLICY IF EXISTS "Authenticated admins can view registrations" ON public.registrations;
DROP POLICY IF EXISTS "Authenticated admins can update registrations" ON public.registrations;

-- Visitors can submit a registration, but cannot read or update registrations.
CREATE POLICY "Public can submit registrations"
  ON public.registrations
  FOR INSERT
  TO anon, authenticated
  WITH CHECK (true);

-- Dashboard data access is limited to Supabase-authenticated users.
CREATE POLICY "Authenticated admins can view registrations"
  ON public.registrations
  FOR SELECT
  TO authenticated
  USING (true);

CREATE POLICY "Authenticated admins can update registrations"
  ON public.registrations
  FOR UPDATE
  TO authenticated
  USING (true)
  WITH CHECK (true);

GRANT INSERT ON public.registrations TO anon, authenticated;
GRANT SELECT, UPDATE ON public.registrations TO authenticated;
GRANT USAGE, SELECT ON SEQUENCE public.registrations_id_seq TO anon, authenticated;

-- 2. Payment screenshot storage bucket
INSERT INTO storage.buckets (id, name, public)
VALUES ('payments', 'payments', TRUE)
ON CONFLICT (id) DO UPDATE SET public = EXCLUDED.public;

-- Remove the upload policy from the earlier version and recreate it.
DROP POLICY IF EXISTS "Allow public payment uploads" ON storage.objects;
DROP POLICY IF EXISTS "Public can upload payment screenshots" ON storage.objects;

-- The bucket being public permits viewing files by URL; this policy permits uploads.
CREATE POLICY "Public can upload payment screenshots"
  ON storage.objects
  FOR INSERT
  TO anon, authenticated
  WITH CHECK (bucket_id = 'payments');

GRANT INSERT ON storage.objects TO anon, authenticated;
