-- HERÈA'26 Database Schema

-- 1. Create the registrations table
CREATE TABLE registrations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  registration_id TEXT UNIQUE NOT NULL,
  full_name TEXT NOT NULL,
  college_name TEXT NOT NULL,
  department TEXT NOT NULL,
  email TEXT NOT NULL,
  whatsapp TEXT NOT NULL,
  selected_event TEXT NOT NULL,
  payment_screenshot TEXT NOT NULL,
  payment_status TEXT DEFAULT 'Pending',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 2. Enable Row Level Security (RLS)
ALTER TABLE registrations ENABLE ROW LEVEL SECURITY;

-- 3. Allow anyone to insert registrations (Public access for the form)
CREATE POLICY "Allow public inserts" ON registrations 
  FOR INSERT 
  WITH CHECK (true);

-- 4. Allow authenticated admins to view all data
CREATE POLICY "Allow authenticated view" ON registrations 
  FOR SELECT 
  USING (auth.role() = 'authenticated');

-- 5. Allow authenticated admins to update payment status
CREATE POLICY "Allow authenticated update" ON registrations 
  FOR UPDATE 
  USING (auth.role() = 'authenticated');

-- 6. Allow unauthenticated visitors using the anon key to upload payment screenshots
-- to the payments bucket. A PUBLIC bucket only enables public reads; it does not
-- grant permission to upload files.
CREATE POLICY "Allow public payment uploads" ON storage.objects
  FOR INSERT
  TO anon
  WITH CHECK (bucket_id = 'payments');

-- NOTE:
-- Create a Storage Bucket named 'payments' and set it to PUBLIC if the admin
-- dashboard should open screenshot URLs without signing in. The policy above
-- grants uploads only to this bucket.
