-- HERÈA'26 Database Schema

-- 1. Create the registrations table
CREATE TABLE registrations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  registration_id TEXT UNIQUE NOT NULL,
  full_name TEXT NOT NULL,
  college_name TEXT NOT NULL,
  department TEXT NOT NULL,
  email TEXT NOT NULL,
  whatsapp TEXT NOT NULL,
  selected_event TEXT NOT NULL,
  payment_screenshot TEXT NOT NULL,
  payment_status TEXT DEFAULT 'Pending',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 2. Enable Row Level Security (RLS)
ALTER TABLE registrations ENABLE ROW LEVEL SECURITY;

-- 3. Allow anyone to insert registrations (Public access for the form)
CREATE POLICY "Allow public inserts" ON registrations 
  FOR INSERT 
  WITH CHECK (true);

-- 4. Allow authenticated admins to view all data
CREATE POLICY "Allow authenticated view" ON registrations 
  FOR SELECT 
  USING (auth.role() = 'authenticated');

-- 5. Allow authenticated admins to update payment status
CREATE POLICY "Allow authenticated update" ON registrations 
  FOR UPDATE 
  USING (auth.role() = 'authenticated');

-- NOTE: 
-- Don't forget to create a Storage Bucket named 'payments'
-- and set it to PUBLIC so users can upload their UPI screenshots.
